/**
 * Русские названия блоков и полей для админки.
 * Сами поля и их типы берутся из схем фронта (src/blocks-schema.json),
 * здесь только подписи, группы и подсказки.
 */

export type BlockMeta = {
  label: string
  group: string
  hint?: string
}

export const BLOCK_GROUPS = {
  hero: 'Вводные',
  main: 'Главная и общие',
  industry: 'Отрасль и направление',
  about: 'О компании и история',
  career: 'Карьера',
  service: 'Услуга',
  project: 'Проект',
  service2: 'Публикации и служебные',
} as const

const g = BLOCK_GROUPS

export const BLOCK_META: Record<string, BlockMeta> = {
  hero: { label: 'Hero главной', group: g.hero, hint: 'Заголовок до 4 строк, два абзаца текста, фон и кнопка' },
  view: { label: 'Hero «О компании»', group: g.hero },
  viewIndustry: { label: 'Hero отрасли', group: g.hero, hint: 'Описание до 400 символов, логотипы клиентов до 4' },
  intro: { label: 'Hero направления', group: g.hero, hint: 'Заголовок до 150, подзаголовок до 250' },
  serviceHero: { label: 'Hero услуги', group: g.hero },
  projectHero: { label: 'Hero проекта', group: g.hero, hint: 'Заголовок до 140' },
  careerHero: { label: 'Hero карьеры', group: g.hero, hint: '6 фото сотрудников, теги 4–10' },
  historyHero: { label: 'Hero истории', group: g.hero },
  contactsHero: { label: 'Hero контактов', group: g.hero },
  policyHero: { label: 'Hero политики', group: g.hero },
  detailHero: { label: 'Hero вакансии', group: g.hero },

  topical: { label: 'Актуальное', group: g.main, hint: 'Минимум 2 карточки' },
  events: { label: 'Мероприятия', group: g.main },
  ideas: { label: 'От идеи до поддержки', group: g.main, hint: 'Заголовок до 200, текст до 300, карточки до 4' },
  industries: { label: 'Отрасли (аккордеон)', group: g.main },
  directions: { label: 'Направления (слайдер)', group: g.main, hint: 'Описание карточки до 500, логотипы до 4' },
  callback: { label: 'Форма обратной связи', group: g.main },
  reviews: { label: 'Отзывы клиентов', group: g.main, hint: 'Слайдер от 3 карточек' },
  faq: { label: 'Вопрос — ответ', group: g.main },
  partners: { label: 'Партнёры (слайдер)', group: g.main },
  vendors: { label: 'Партнёры (с кнопкой)', group: g.main },
  leader: { label: 'Лидер направления', group: g.main },
  expert: { label: 'Остались вопросы (эксперт)', group: g.main },
  similarNews: { label: 'Похожие публикации', group: g.main, hint: 'Меньше 2 карточек — блок скрыт' },
  similarProjects: { label: 'Похожие проекты', group: g.main, hint: 'Меньше 2 карточек — блок скрыт' },

  aboutIndustry: { label: 'Об отрасли', group: g.industry, hint: 'Ключевых решений — до 8' },
  solutions: { label: 'Услуги и решения отрасли', group: g.industry },
  examples: { label: 'Примеры задач (подробно)', group: g.industry, hint: 'Заголовок до 80, решение до 500, метрики 1–3' },
  future: { label: 'Примеры задач (кейсы)', group: g.industry },
  cases: { label: 'Какие задачи мы решали', group: g.industry, hint: 'До 3 карточек' },
  description: { label: 'О направлении', group: g.industry, hint: 'Текст до 1200 символов' },
  services: { label: 'Услуги направления', group: g.industry },
  otherDirections: { label: 'Другие направления', group: g.industry },

  valuation: { label: 'Ценности', group: g.about, hint: '5 карточек: лейбл до 30, заголовок до 60, описание до 150' },
  expertise: { label: 'Экспертиза (табы)', group: g.about, hint: 'Название таба до 19 символов' },
  award: { label: 'Награды', group: g.about },
  team: { label: 'Команда', group: g.about },
  historyCompany: { label: 'История (анонс)', group: g.about },
  sectors: { label: 'Отрасли и направления', group: g.about },
  contacts: { label: 'Контакты (на «О компании»)', group: g.about },
  history: { label: 'Период истории', group: g.about },

  careerVideo: { label: 'Видео', group: g.career, hint: 'mp4 до 30 секунд или ссылка на плеер' },
  about: { label: 'О компании (карьера)', group: g.career, hint: 'Метрики до 5' },
  stack: { label: 'Технологический стек', group: g.career, hint: 'Иконки SVG/PNG на прозрачном фоне, до 20' },
  benefits: { label: 'Почему выбирают нас', group: g.career, hint: '4–10 пунктов' },
  offers: { label: 'Стажировки', group: g.career, hint: 'До 4 карточек' },
  gallery: { label: 'Жизнь в компании', group: g.career, hint: 'Не меньше 3 фото, до 4 соцсетей' },
  banners: { label: 'Вакансии / стажировки', group: g.career },
  aboutDirection: { label: 'О центре экспертизы', group: g.career },
  aboutVacancy: { label: 'О вакансии / Будет плюсом', group: g.career },
  advantages: { label: 'Что мы предлагаем', group: g.career, hint: 'До 10 пунктов' },
  similar: { label: 'Похожие вакансии', group: g.career },

  serviceText: { label: 'Текстовый блок', group: g.service },
  serviceImgText: { label: 'Текст с картинкой', group: g.service },
  serviceImg: { label: 'Блок с изображением', group: g.service, hint: 'По клику открывается в попапе' },
  cards: { label: 'Блок с карточками', group: g.service },
  serviceList: { label: 'Список', group: g.service },
  serviceContent: { label: 'Список с подзаголовками', group: g.service },
  serviceTable: { label: 'Список в две колонки', group: g.service },
  information: { label: 'Почему нам доверяют', group: g.service },
  stages: { label: 'Этапы реализации', group: g.service },
  steps: { label: 'Таймлайн', group: g.service, hint: 'Пункты до 50 символов' },
  relatedServices: { label: 'Связанные услуги', group: g.service },

  results: { label: 'Результат (цифры)', group: g.project, hint: '2–6 карточек, значение до 6 символов' },
  goals: { label: 'Цели и задачи', group: g.project },
  decision: { label: 'Решение', group: g.project },
  realization: { label: 'Реализация', group: g.project, hint: 'До 5000 символов' },
  transformation: { label: 'Трансформация', group: g.project },
  outcomes: { label: 'Чего удалось достичь', group: g.project, hint: '4–8 пунктов' },
  plans: { label: 'Планы развития', group: g.project, hint: 'Текст до 500' },
  feedback: { label: 'Видеоотзыв', group: g.project },

  newsDetail: { label: 'Тело публикации', group: g.service2 },
  journal: { label: 'Журнал', group: g.service2, hint: 'Заголовок до 150, описание до 500' },
  companions: { label: 'Список партнёров', group: g.service2 },
  policyItem: { label: 'Политика: раздел', group: g.service2 },
  policyTable: { label: 'Политика: таблица целей', group: g.service2 },
  policyContacts: { label: 'Политика: контакты', group: g.service2 },
  offices: { label: 'Офисы', group: g.service2 },
  details: { label: 'Реквизиты', group: g.service2 },
  documents: { label: 'Тендерная документация', group: g.service2 },
  activities: { label: 'Коды деятельности', group: g.service2 },
}

/** Подписи полей по имени ключа в схеме фронта. */
export const FIELD_LABELS: Record<string, string> = {
  acceptedFileTypes: 'Типы файлов',
  action: 'Адрес отправки',
  addContent: 'Дополнительно',
  alt: 'Alt-текст',
  background: 'Фон',
  breadcrumbs: 'Хлебные крошки',
  btn: 'Кнопка',
  btnCall: 'Кнопка звонка',
  btnScroll: 'Кнопка прокрутки',
  caption: 'Подпись',
  card: 'Карточка',
  cities: 'Города',
  codes: 'Коды',
  columns: 'Заголовки колонок',
  companies: 'Логотипы компаний',
  company: 'Компании',
  content: 'Содержимое',
  count: 'Количество',
  data: 'Данные',
  date: 'Дата',
  description: 'Описание',
  desktop: 'Для десктопа',
  fields: 'Поля',
  footer: 'Футер',
  form: 'Форма',
  format: 'Формат',
  hash: 'Якорь',
  hashToScroll: 'Якорь для кнопки',
  header: 'Хедер',
  icon: 'Иконка',
  images: 'Фото',
  img: 'Картинка',
  isActive: 'Выделить',
  isDefault: 'Открыт по умолчанию',
  isOpen: 'Открыт',
  item: 'Карточка',
  items: 'Элементы',
  keywords: 'Keywords',
  label: 'Подпись',
  legalBasis: 'Правовое основание',
  link: 'Ссылка',
  menu: 'Меню',
  name: 'Имя',
  navTitle: 'Название в навигации',
  offices: 'Офисы',
  person: 'Сотрудник',
  phone: 'Телефон',
  placeholder: 'Подсказка в поле',
  position: 'Должность',
  postion: 'Должность',
  preview: 'Обложка',
  processedData: 'Обрабатываемые данные',
  purpose: 'Цель',
  quote: 'Цитата',
  robots: 'Robots',
  secondTitle: 'Второй заголовок',
  slug: 'Ссылка (символьный код)',
  socials: 'Соцсети',
  speech: 'Текст цитаты',
  src: 'Файл',
  stats: 'Цифры',
  storagePeriod: 'Срок хранения',
  subTitle: 'Подзаголовок',
  subtitle: 'Подзаголовок',
  supTag: 'Верхняя метка',
  suptitle: 'Надзаголовок',
  tablet: 'Для планшета',
  tag: 'Надзаголовок',
  tags: 'Теги',
  text: 'Текст',
  time: 'Время',
  title: 'Заголовок',
  total: 'Всего',
  type: 'Тип',
  url: 'Ссылка',
  urlData: 'Параметры фильтра',
  value: 'Значение',
  variant: 'Вариант',
  video: 'Видео',
}

/** Подписи значений select-полей. Пустое значение фронта хранится как «default». */
export const OPTION_LABELS: Record<string, string> = {
  default: 'Обычный',
  h1: 'H1',
  h2: 'H2',
  image: 'Картинка',
  video: 'Видео',
  mixed: 'Авто (по расширению файла)',
  marker: 'Маркированный',
  order: 'Нумерованный',
  html: 'Текст',
  quote: 'Цитата',
  table: 'Таблица',
  media: 'Картинка или видео',
  speech: 'Реплика',
  activities__itemWrap_bgGray: 'Серый фон',
  breadcrumbs_blue: 'Синие',
  cards_columns_2: 'Две колонки',
  fullscreen: 'На всю ширину',
  history_rotate: 'Наклон фона',
  information_list: 'Одна колонка',
  newsDetailQuote_bgGray: 'Серый фон',
  newsDetailQuote_bgLime: 'Лаймовый фон',
  policyItem_last: 'Последний раздел',
  reviews_lime: 'Лаймовый',
  serviceText_bgLime: 'Лаймовый',
  withBg: 'С фоном',
}

/** Поля, где текста много: показываем textarea. HTML-разметка во всех текстовых полях допустима. */
export const LONG_TEXT_KEYS = new Set([
  'description', 'text', 'speech', 'subtitle', 'subTitle', 'processedData', 'legalBasis', 'purpose',
])
